### ISSUE TITLE
Lucee 5 compatibility

### ISSUE THREAD

**Issue by chrisdpeters** [Leftbower/cfspreadsheet-lucee#2]
@paulklinkenberg updated this extension so it's in the new `.lex` format for Lucee 5. (See attached: [cfspreadsheet-lucee5.zip](https://github.com/Leftbower/cfspreadsheet-lucee/files/186069/cfspreadsheet-lucee5.zip), which should be changed to a `.lex` extension, but GitHub would only allow me to upload a zip.)

I'm not sure what strategy you would like to use for versioning and such (I'm assuming this makes it _not_ work with Lucee 4.5). Maybe you can create a `lucee-4` branch to maintain the current extension and then make `master` all about the new format?

Or should I just open my own repo with the newly formatted extension? I figured I'd run this by you before doing anything further.

**Comment by chrisdpeters** [comment]
Some additional notes from @paulklinkenberg:

> Meanwhile, I have been chatting with Michael Offner, talking about the impossibilities I encountered while creating the extension.
> 
> There are 2 things that will likely change:
> - the jar files will become OSGi bundles, being loaded only when they are used
> - The Spreadsheet.cfc file will be added to  /WEB-INF/lucee/components/

**Comment by Leftbower** [comment]
Hello Chris. I have been working on a 5.0 version as well. The issues I have had seem to mirror those you/Paul list here. I can manually move files to get the extension to work in L5, but the auto-deploy fails. One thing to note is that the jars required seem to already be installed in L5. The key then is getting the cfc file added to the components directory.

I tried the zip you attached and it appears to also have these issues - are you able to make it work, or just restating the jar and cfc in components dir issues?

I've written a script to do this locally while I test other apps on L5. Likewise I have modified for server-wide installation rather than just web context.

**Comment by paulklinkenberg** [comment]
Hi Andrew, the zip file, when renamed to *.lex, should auto-deploy just fine. If you encounter issues, can you send me the deploy.log / the error stack trace?
Micha is now aware of these issues, and said he would look into it:
- [osgi/jar error when adding Apache poi jars to Lucee](https://luceeserver.atlassian.net/browse/LDEV-796)
- [Components in .lex extensions can't be deployed to {lucee-web}/components/](https://luceeserver.atlassian.net/browse/LDEV-797)
  Until that's fixed, I added the spreadsheet.cfc to the webroot, and the jars next to it. I also changed the loadPoi method to not use javaLoader, but instead:

```
<cffunction name="loadPoi" access="private" output="false" returntype="any">
    <cfargument name="javaclass" type="string" required="true" hint="I am the java class to be loaded" />
    <cfparam name="variables.jarPaths" default="#directoryList(getDirectoryFromPath(getCurrentTemplatePath()) & 'lib/', false, 'path', '*.jar').toList()#" />
    <cfreturn createObject("java", javaclass, variables.jarPaths) />
</cffunction>
```

**Comment by paulklinkenberg** [comment]
By the way, is there a specific reason the project was forked away from teamcfadvance? I am quite sure they would love to see the changes as a pull request for their own repo...

**Comment by Leftbower** [comment]
Well short answer: no one was modifying it to work with Lucee (the Team
CFAdvance was Railo only). I modified it on my own for my own use when I
switched to Lucee. Someone (I forget who on the Lucee group) asked if I
would throw what I had done up on github so that they could use it too... I
did not even have a github account so I created just for this. The 2
versions are incompatible with each other as the railo/lucee references
were hard-coded.

Also, I thought Team CF Advance was defunct? Their google group has been
pretty much dormant?

My apologies if I broke some sort of social construct! :)

**Comment by Leftbower** [comment]
Paul - re: auto-deploy... correct: it auto-deploys, I meant it had the same issues of requiring the spreadsheet.cfc to be manually moved over, i.e. it doesn't work out of the box. I've resorted to using a quick script to deploy it to contexts rather than bother with the extension mechanism until it's fixed.

**Comment by paulklinkenberg** [comment]
It should now auto-deploy, and work correctly just by using the .lex extension. The component is placed in the webroot, whiere it should be picked up when the script refers to org.cfpoi.spreadsheet.Spreadsheet()

I testes this with the latest express version, 5.0.0.219

Kind regards,

Paul Klinkenberg

---

**Comment by paulklinkenberg** [comment]
Hey Andrew,
Team CF advance indeed isn't too active it seems, and the fact that you contribute to the community is a great thing off course! I learnt the last couple of years it is good practice to keep opensource projects in one place, unless there is a really good reason to fork it (MariaDB, LibreOffice, Lucee, etc.) It's the spirit of open source, having the community contribute to the same thing / improving existing projects.

I have the intention of adding an ANT build script to this project (copy-pasted from [here](https://github.com/paulklinkenberg/lucee-loganalyzer-installer#includes-complete-ant-build-code-for-lucee-plugins)), which would create the Railo extension + the Lucee 4 extension + the Lucee 5 extension. Also, there would be no more need to use the extensionProvider method, since you can upload extensions into Railo 4 and Lucee 4, if the config.xml in the extension has certain settings available.
But, that will have yet to come. I will wait untill the Lucee 5 bugs are sorted out.

So just to be clear, thanks for contributing :)
Kind regards, Paul

**Comment by chrisdpeters** [comment]
A note on this: the auto-deploy works fine if you install in `{web}/deploy` but not `{server-context}/deploy`. I believe that is what @paulklinkenberg is outlining with those issues he links to above, right?

For example, I had to install in this location in my [Docker/NGINX install](https://github.com/lucee/lucee-dockerfiles/tree/master/lucee-nginx/5.0) (which uses Lucee 5.0.0.228): `/opt/lucee/web/deploy`.

I get an error about it not finding the `Spreadsheet.cfc` component if I install here: `/opt/lucee/server/lucee-server/deploy`

**Comment by Leftbower** [comment]
Chris - I actually received that same error when deploying in the web context, but perhaps it was an older version of Paul's that I had tried (the one from your original link above)?

**Comment by chrisdpeters** [comment]
@Leftbower I am using the one from my original link above.

**Comment by modius** [comment]
@chrisdpeters do you have an example of installing the extension in Docker?  We currently COPY everything manually into place but i don't think its particularly elegant.

For example:

```
FROM lucee/lucee4-nginx:latest

# Install cfspreadsheet for Lucee; https://github.com/Leftbower/cfspreadsheet-lucee
COPY config/cfspreadsheet/org/          /opt/lucee/web/components/org/
COPY config/cfspreadsheet/function/     /opt/lucee/web/library/function/
COPY config/cfspreadsheet/tag/      /opt/lucee/web/library/tag/
COPY config/cfspreadsheet/lib/      /opt/lucee/web/lib/
```

**Comment by chrisdpeters** [comment]
@modius I'd have no idea how to do it for Lucee 4, but Lucee 5 is pretty simple (which is why I've been pushing to get everything working for 5).

Just place the `.lex` file in an `extensions` folder in your project root, then add this to your `Dockerfile`:

```
# Lucee extensions
ADD ./extensions/ /opt/lucee/web/deploy/
```

I guess `COPY` would probably make sense here too.

**Comment by vikaskanani** [comment]
Since the Lucee 5 is officially out, can someone test if it works on that. I didn't get success.

**Comment by chrisdpeters** [comment]
@vikaskanani It is working fine for me on the latest Lucee 5/Tomcat release: [5.0.0-t8.0.36](https://github.com/lucee/lucee-dockerfiles/releases/tag/5.0.0-t8.0.36).

Are you experiencing a specific error? "I didn't get success" helps no one.

**Comment by Leftbower** [comment]
I revised for Lucee 5 (server only) here if someone wants to try:
[https://github.com/Leftbower/cfspreadsheet-lucee-5](https://github.com/Leftbower/cfspreadsheet-lucee-5)

**Comment by vikaskanani** [comment]
@chrisdpeters Copy `.lex` file in deploy folder method works. I was trying to upload `.lex` in web-context which throws 404 page not found error.

**Comment by Leftbower** [comment]
@vikaskanani - are you using the .lex from the link I provided ([https://github.com/Leftbower/cfspreadsheet-lucee-5](https://github.com/Leftbower/cfspreadsheet-lucee-5))

If so, that extension will not work with the web context yet, only the server (until the issues listed on the readme are fixed by the LAS team). You can of course, always manually move the required files over into any context you want

**Comment by Leftbower** [comment]
For Lucee 5, please use this extension here: [https://github.com/Leftbower/cfspreadsheet-lucee-5](https://github.com/Leftbower/cfspreadsheet-lucee-5)
